I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1109, in script
    makara "Benar"
  File "game/Quiz.rpy", line 14, in execute
    screen quiz_kedua():
  File "game/Quiz.rpy", line 14, in execute
    screen quiz_kedua():
  File "game/Quiz.rpy", line 15, in execute
    hbox:
  File "game/Quiz.rpy", line 19, in execute
    imagebutton:
Exception: Imagebutton does not have a idle image. (auto='images/quiz/quiz_2_1_%s.png').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1109, in script
    makara "Benar"
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 2572, in execute
    Say.execute(self)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\character.py", line 1451, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\character.py", line 1102, in do_display
    display_say(who,
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\character.py", line 799, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\core.py", line 2188, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\core.py", line 2705, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\core.py", line 2705, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/Quiz.rpy", line 14, in execute
    screen quiz_kedua():
  File "game/Quiz.rpy", line 14, in execute
    screen quiz_kedua():
  File "game/Quiz.rpy", line 15, in execute
    hbox:
  File "game/Quiz.rpy", line 19, in execute
    imagebutton:
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ui.py", line 975, in _imagebutton
    idle = choice(idle, idle_image, "idle", required=True)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ui.py", line 969, in choice
    raise Exception("Imagebutton does not have a %s image. (auto=%r)." % (name, auto))
Exception: Imagebutton does not have a idle image. (auto='images/quiz/quiz_2_1_%s.png').

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.0.24082114
 
Sun Dec  8 00:17:39 2024
